# Generated by Django 2.0.3 on 2018-03-19 00:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date_time', models.DateTimeField(null=True)),
                ('match_description', models.TextField(null=True)),
                ('competition_name', models.CharField(blank=True, max_length=250)),
                ('match_status', models.IntegerField(choices=[(1, 'Coming'), (2, 'Today'), (3, 'Fineshed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('team_country', models.CharField(max_length=250)),
                ('team_details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField()),
                ('seat_no', models.IntegerField(blank=True, default=0)),
                ('barcode_image', models.ImageField(blank=True, upload_to='img/')),
                ('payment_method', models.CharField(choices=[(0, 'Online'), (1, 'On delivery')], max_length=250, null=True)),
                ('ticket_class', models.CharField(choices=[(0, 'basic'), (1, 'mid'), (3, 'first')], max_length=250, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stad.Match')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserved_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stad.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='stad.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='stad.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stad.Arena'),
        ),
    ]
