# Generated by Django 2.0.3 on 2018-03-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='arena_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
