# Generated by Django 2.0.3 on 2018-03-20 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0002_arena_arena_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=models.IntegerField(default=0), null=True), size=None),
        ),
    ]
