# Generated by Django 2.0.3 on 2018-03-20 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0005_auto_20180320_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, null=True, size=None),
        ),
    ]
