# Generated by Django 2.0.3 on 2018-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0007_remove_ticket_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
