# Generated by Django 2.0.3 on 2018-03-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0010_auto_20180325_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='size',
        ),
    ]
