# Generated by Django 2.0.3 on 2018-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0013_match_match_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_result',
            new_name='awayteam_result',
        ),
        migrations.AddField(
            model_name='match',
            name='hometeam_result',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
