# Generated by Django 2.0.3 on 2018-03-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0014_auto_20180326_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_name',
            field=models.CharField(blank=True, choices=[(0, 'AlManaseer League'), (1, 'AlManaseer Cup'), (2, 'AlManaseer Shield')], max_length=250),
        ),
    ]
