# Generated by Django 2.0.3 on 2018-03-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0015_auto_20180326_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_name',
            field=models.CharField(blank=True, choices=[('AlManaseer League', 'AlManaseer League'), ('AlManaseer Cup', 'AlManaseer Cup'), ('AlManaseer Shield', 'AlManaseer Shield')], max_length=250),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stad.Arena'),
        ),
    ]
