# Generated by Django 2.0.3 on 2018-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stad', '0017_auto_20180326_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Coming'), (2, 'Today'), (3, 'Fineshed')], default=1, null=True),
        ),
    ]
